# Generated by Django 5.0 on 2023-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('DPI', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
