# Generated by Django 5.0 on 2023-12-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=100)),
                ('DescProducto', models.CharField(max_length=100)),
                ('PrecioProducto', models.IntegerField()),
            ],
        ),
    ]
