# Generated by Django 5.0 on 2023-12-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('DPI', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.supervisor')),
            ],
        ),
    ]
