# Generated by Django 5.0 on 2023-12-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Cantidad', models.CharField(max_length=100)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('Total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.supervisor')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.vendedor')),
            ],
        ),
    ]
