# Generated by Django 5.0 on 2023-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Total',
            field=models.IntegerField(),
        ),
    ]
