# Generated by Django 5.0 on 2023-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_pedido_cantidad_alter_pedido_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
    ]
